Задача
spectrdort/kurs_yandex pull request #5
Opened 2021-05-17 08:55 UTC by spectrdort

Напишите функцию UpdateIfGreater, которая принимает два целочисленных аргумента: first и second. Если first оказался больше second, Ваша функция должна записывать в second значение параметра first. При этом указанная функция не должна ничего возвращать, а изменение параметра second должно быть видно на вызывающей стороне.

Пример

int a = 4;
int b = 2;
UpdateIfGreater(a, b);
// b должно стать равно 4
Замечание

В данной задаче вам нужно самостоятельно выбрать типы для параметров функции UpdateIfGreater. Подумайте, какой из них обязан быть ссылкой, а какой может быть просто int. При этом учтите разные варианты вызова функции:

UpdateIfGreater(x, y);
UpdateIfGreater(5, y);

2021-05-17 10:13 UTC, Duwaz requested changes

2021-05-17 10:13 UTC, Duwaz commented on Белый пояс/Неделя 2/1. Функции/4. Максимизатор/main.cpp
> +﻿void UpdateIfGreater(char first, char& second)
В примере задачи указано:
```int a = 4;```
А у тебя аргументом является char. Уверен, что это верное решение?

2021-05-17 10:16 UTC, spectrdort commented on Белый пояс/Неделя 2/1. Функции/4. Максимизатор/main.cpp
> +﻿void UpdateIfGreater(char first, char& second)
Да, ниже написано учитывайте, что функция может вызываться с аргументами x, y; 5, y
Или я что-то не правильно понял?

2021-05-17 10:17 UTC, spectrdort commented on Белый пояс/Неделя 2/1. Функции/4. Максимизатор/main.cpp
> +﻿void UpdateIfGreater(char first, char& second)
Или под этим подразумевается что может быть заданное значение и введённое?

2021-05-17 10:26 UTC, Duwaz commented on Белый пояс/Неделя 2/1. Функции/4. Максимизатор/main.cpp
> +﻿void UpdateIfGreater(char first, char& second)
Думаю, подразумевалось, что функция может вызываться так:
```UpdateIfGreater(x, y)```
где x и y - int'ы. А не
```UpdateIfGreater('x', 'y')```
Как ты подумал.

2021-05-17 10:32 UTC, spectrdort commented on Белый пояс/Неделя 2/1. Функции/4. Максимизатор/main.cpp
> +﻿void UpdateIfGreater(char first, char& second)
Убедил

2021-06-05 14:19 UTC, Duwaz approved these changes

2021-06-05 14:19 UTC, merged