Перемещение строк
spectrdort/kurs_yandex pull request #6
Opened 2021-05-17 08:58 UTC by spectrdort

Напишите функцию MoveStrings, которая принимает два вектора строк, source и destination, и дописывает все строки из первого вектора в конец второго. После выполнения функции вектор source должен оказаться пустым.

2021-05-17 10:13 UTC, Duwaz requested changes

2021-05-17 10:13 UTC, Duwaz commented on Белый пояс/Неделя 2/1. Функции/5. Перемещение строк/Perem.strok.cpp
> +	for (int i = 0; i < sourse.size(); ++i)
Думаю, можно реализовать эту логику без for'а.

2021-05-17 10:23 UTC, spectrdort commented on Белый пояс/Неделя 2/1. Функции/5. Перемещение строк/Perem.strok.cpp
> +	for (int i = 0; i < sourse.size(); ++i)
1

2021-06-12 12:07 UTC, Duwaz approved these changes

2021-06-12 12:07 UTC, merged