Разворот последовательности - 2
spectrdort/kurs_yandex pull request #8
Opened 2021-05-18 18:14 UTC by spectrdort

2021-05-19 11:16 UTC, Duwaz commented on Белый пояс/Неделя 2/1. Функции/Разв/main.cpp
> +﻿#include <vector>
Лишний файл?

2021-05-19 11:38 UTC, spectrdort commented on Белый пояс/Неделя 2/1. Функции/Разв/main.cpp
> +﻿#include <vector>
Да, пытался удалить, но, видимо, пока пул реквест не закрыт - не удалить

2021-05-19 11:59 UTC, Duwaz requested changes

2021-05-19 11:59 UTC, Duwaz commented on Белый пояс/Неделя 2/1. Функции/Разв/main.cpp
> +﻿#include <vector>
А сейчас?

2021-06-12 12:20 UTC, Duwaz approved these changes

2021-06-12 12:21 UTC, merged